### ISSUE TITLE
How to copy bootable disk to a new drive?

### ISSUE THREAD

**Issue by Turingrun** [syno-community/rr#3]
hello, i write rr.img to a  sd card as  the boot disk,but now i have another sata disk, and i want use it replace sd card to boot synology dsm.
I try to use dd command to copy the first two partition to new sata disk,and copy third partition'data to new disk,but it does not work.

**Comment by syno-community** [comment]
I think you should not use a SATA drive to boot.
Firstly, it is a waste of a drive just to boot because a sata drive has a very large capacity when compared to a USB with only a few GB.
Second, it will be very difficult for you to update the next versions of the bootload, and there will always be a message that there is an unused drive.
If you create a pool and use it, you will immediately be unable to boot.

**Comment by syno-community** [comment]
If you still want to do it, simply use any disk imaging software to burn rr.img to the hdd.
One of the things the software can do is: https://etcher.balena.io/#download-etcher
